Network = "udp"
Curve = "bn256/cf"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
   Nodes = 64
   Threshold = 34
   Failing = 20
   Processes = 8
   [Runs.Handel]
       Period = "10ms"
       UpdateCount = 1
       NodeCount = 10
       Timeout = "50ms"
       UnsafeSleepTimeOnSigVerify = 1



[[Runs]]
   Nodes = 256
   Threshold = 200
   Failing = 21
   Processes = 8
   [Runs.Handel]
       Period = "10ms"
       UpdateCount = 1
       NodeCount = 10
       Timeout = "50ms"
       UnsafeSleepTimeOnSigVerify = 1
