Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1
Simulation = "gossip"


[[Runs]]
    Nodes = 32
    Threshold = 32
    Processes = 2
    [Runs.Extra]
        Connector = "neighbor"
        Count = "5"
