Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1
Simulation = "p2p/libp2p"


[[Runs]]
    Nodes = 16
    Threshold = 16
    Processes = 1
    [Runs.Extra]
        Connector = "neighbor"
        Count = "10"
