Network = "udp"
Curve = "bn256/cf"
Encoding = "gob"
MonitorPort = 9980
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
    Nodes = 4
    Threshold = 3
    Failing = 0
    Byzantines = 1
    Processes = 4
    [Runs.Handel]
        Period = "10ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "50ms"
        UnsafeSleepTimeOnSigVerify = 0
