Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
    Nodes = 180
    Threshold = 178
    Failing = 2
    Processes = 1
    [Runs.Handel]
        Period = "10ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "100ms"
