Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1
Simulation = "p2p/udp"


[[Runs]]
    Nodes = 4
    Threshold = 4
    Processes = 2

[[Runs]]
    Nodes = 4
    Threshold = 4
    Processes = 2
    [Runs.Extra]
        AggAndVerify = "1"  
