Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "random"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 500
  Threshold = 480
  Failing = 0
  Processes = 500
    [Runs.Handel]
      Period = "10ms"
      UpdateCount = 1
      NodeCount = 10
      Timeout = "50ms"
      UnsafeSleepTimeOnSigVerify = 0
