Network = "udp"
Curve = "bn256/cf"
Encoding = "gob"
MonitorPort = 9980
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
    Nodes = 64
    Threshold = 34
    Failing = 20
    Processes = 2
    [Runs.Handel]
        Period = "10ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "50ms"
        UnsafeSleepTimeOnSigVerify = 0
        Evaluator = "store"
