Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "random"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 2000
  Threshold = 1010
  Failing = 20
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
[[Runs]]
  Nodes = 2000
  Threshold = 1010
  Failing = 250
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
[[Runs]]
  Nodes = 2000
  Threshold = 1010
  Failing = 500
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
[[Runs]]
      Nodes = 2000
      Threshold = 1010
      Failing = 750
      Processes = 1000
      [Runs.Handel]
        Period = "10ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "50ms"
        UnsafeSleepTimeOnSigVerify = 0
[[Runs]]
  Nodes = 2000
  Threshold = 1010
  Failing = 990
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

