Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "p2p/udp"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 100
  Threshold = 99
  Failing = 0
  Processes = 50
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"

[[Runs]]
  Nodes = 1000
  Threshold = 990
  Failing = 0
  Processes = 500
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"

[[Runs]]
  Nodes = 2000
  Threshold = 1980
  Failing = 0
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"
