Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "p2p/udp"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""
[[Runs]]
  Nodes = 400
  Threshold = 380
  Failing = 0
  Processes = 400
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"
[[Runs]]
  Nodes = 1000
  Threshold = 950
  Failing = 0
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"
[[Runs]]
  Nodes = 2000
  Threshold = 1900
  Failing = 0
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "0"
[[Runs]]
  Nodes = 400
  Threshold = 380
  Failing = 0
  Processes = 400
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "1"
[[Runs]]
  Nodes = 1000
  Threshold = 950
  Failing = 0
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "1"
[[Runs]]
  Nodes = 2000
  Threshold = 1900
  Failing = 0
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
  [Runs.Extra]
    AggAndVerify = "1"
